apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  selector:
    matchLabels:
      name: python-pod
      app: gcp-app
  template:
    metadata:
      labels:
        name: python-pod
        app: gcp-app
    spec:
      containers:
      - name: python-container
        image: gcr.io/mohamedadeltaha/python-app
        resources:
        ports:
        - containerPort: 8000
        env:
          - name: ENVIRONMENT
            value: DEV
          - name: HOST
            value: "localhost"
          - name: PORT
            value: "8000"
          - name: REDIS_HOST
            value: "redis-service"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_DB
            value: "0"