apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  labels:
    app: gcp-app
spec:
  type: LoadBalancer
  selector:
    name: python-pod
    app: gcp-app
  ports:
  - port: 8000
    targetPort: 8000