apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp-app
  template:
    metadata:
      labels:
        app: gcp-app
    spec:
      containers:
      - name: redis-container
        image: redis
        ports:
        - containerPort: 6379