apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: gcp-app
spec:
  selector:
    name: redis-pod
    app: gcp-app
  ports:
  - port: 6379
    targetPort: 6379